services:
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb+srv://bsse1405:kodZR14XNlhr0MD6@cluster0.txmylhj.mongodb.net/
      - PORT=3001
      - LOAN_SERVICE_URL=http://loan-service:3003/api/loans
    networks:
      - library-network
    restart: unless-stopped

  book-service:
    build: ./book-service
    container_name: book-service
    ports:
      - "3002:3002"
    environment:
      - MONGODB_URI=mongodb+srv://bsse1405:AC08nfisABbCZpv7@cluster0.bgndrmx.mongodb.net/
      - PORT=3002
    networks:
      - library-network
    restart: unless-stopped

  loan-service:
    build: ./loan-service
    container_name: loan-service
    ports:
      - "3003:3003"
    environment:
      - MONGO_URI=mongodb+srv://bsse1405:FVxPorbJclmVWCMl@cluster0.zze23wl.mongodb.net/
      - PORT=3003
      - BOOK_SERVICE_URL=http://book-service:3002/api/books
      - USER_SERVICE_URL=http://user-service:3001/api/users
    networks:
      - library-network
    depends_on:
      - user-service
      - book-service
    restart: unless-stopped

  nginx-gateway:
    build: ./nginx
    container_name: nginx-config
    ports:
      - "8080:8080"
    networks:
      - library-network
    depends_on:
      - user-service
      - book-service
      - loan-service

networks:
  library-network:
    driver: bridge